<?php

return [
    'nav' => ['home' => 'Beranda', 'vault' => 'Brankas', 'activity' => 'Aktivitas', 'security' => 'Keamanan', 'notifications' => 'Notifikasi', 'profile' => 'Profil'],
    'common' => ['continue' => 'Lanjut', 'cancel' => 'Batal', 'email' => 'Surel', 'password' => 'Kata sandi', 'logout' => 'Keluar', 'user' => 'Pengguna', 'no_role' => 'Belum ada role', 'language' => 'Bahasa', 'save' => 'Simpan', 'or' => 'atau', 'navigation' => 'Navigasi', 'toggle_password' => 'Tampilkan atau sembunyikan kata sandi', 'dismiss' => 'Tutup notifikasi', 'double_back_to_close' => 'Tekan kembali sekali lagi untuk keluar'],
    'startup' => ['checking' => 'Mengecek sesi Anda'],
    'auth' => [
        'login' => ['title' => 'Masuk', 'heading' => 'Masuk', 'subtitle' => 'Surel dan kata sandi dulu, kode 2FA setelahnya jika aktif.', 'password_placeholder' => 'Kata sandi akun', 'submit' => 'Login', 'signup' => 'Buat akun baru', 'forgot' => 'Lupa kata sandi?', 'no_access' => 'Belum punya akses?'],
        'signup' => ['title' => 'Daftar', 'heading' => 'Buat akun', 'subtitle' => 'Isi detail dasar untuk akses mobile.', 'name' => 'Nama', 'name_placeholder' => 'Nama lengkap', 'password_placeholder' => 'Minimal 8 karakter', 'confirm' => 'Konfirmasi password', 'confirm_placeholder' => 'Ulangi password', 'submit' => 'Buat akun', 'login' => 'Sudah punya akun'],
        'forgot' => ['title' => 'Atur Ulang Kata Sandi', 'heading' => 'Atur ulang kata sandi', 'subtitle' => 'Masukkan surel akun. Jika valid, API akan mengirim link reset.', 'submit' => 'Kirim link reset', 'back' => 'Kembali masuk', 'sent' => 'Link reset kata sandi sudah dikirim jika surel valid.'],
        'reset' => ['title' => 'Kata Sandi Baru', 'heading' => 'Kata sandi baru', 'subtitle' => 'Gunakan token reset dari surel untuk mengganti kata sandi akun.', 'token' => 'Token reset', 'token_placeholder' => 'Token dari surel', 'password' => 'Kata sandi baru', 'submit' => 'Simpan kata sandi', 'done' => 'Kata sandi berhasil direset. Silakan masuk.'],
        'two_factor' => ['title' => 'Verifikasi', 'heading' => 'Kode 2FA', 'subtitle' => 'Masukkan kode 6 digit dari aplikasi authenticator untuk melanjutkan.', 'code' => 'Kode authenticator', 'use_recovery_code' => 'Gunakan kode pemulihan', 'recovery_code' => 'Kode pemulihan', 'recovery_code_help' => 'Gunakan salah satu kode pemulihan yang sudah Anda simpan jika aplikasi authenticator tidak tersedia.', 'submit' => 'Verifikasi', 'back' => 'Kembali masuk', 'restart' => 'Mulai lagi dengan surel dan kata sandi.', 'expired' => 'Sesi verifikasi 2FA berakhir. Masuk ulang.'],
        'registration_disabled' => 'Registrasi sedang dinonaktifkan.', 'missing_token' => 'Respons login tidak membawa token Sanctum.', 'email_hint' => 'Periksa surel akun.', 'password_mismatch' => 'Surel atau kata sandi tidak cocok.', 'signed_out' => 'Anda sudah keluar.',
    ],
    'profile' => ['title' => 'Profil', 'email_missing' => 'Surel belum tersedia', 'security' => 'Keamanan', 'tab_profile' => 'Profil', 'tab_security' => 'Keamanan', 'security_subtitle' => 'Kata sandi dan autentikasi dua faktor', 'language_subtitle' => 'Pilih bahasa app dan respons API', 'language_saved' => 'Bahasa diperbarui.', 'edit' => 'Edit profil', 'name' => 'Nama', 'save' => 'Simpan profil', 'updated' => 'Profil berhasil diperbarui.'],
    'home' => ['title' => 'Beranda', 'welcome' => 'Selamat datang', 'account_overview' => 'Ringkasan akun', 'verified' => 'Terverifikasi', 'score' => ':score/100', 'active_access' => 'Grup akses aktif', 'security_score' => 'Skor keamanan', 'quick_actions' => 'Aksi cepat', 'recent_activity' => 'Aktivitas terbaru', 'view_all' => 'Lihat semua', 'no_activity' => 'Tidak ada risiko terbaru'],
    'notifications' => ['title' => 'Notifikasi', 'mark_all' => 'Tandai semua terbaca', 'fallback_title' => 'Notifikasi', 'read' => 'Baca', 'empty' => 'Belum ada notifikasi.', 'one_read' => 'Notifikasi ditandai terbaca.', 'all_read' => 'Semua notifikasi ditandai terbaca.', 'levels' => ['info' => 'Informasi', 'success' => 'Sukses', 'warning' => 'Peringatan', 'error' => 'Kesalahan']],
    'security' => ['title' => 'Keamanan', 'status' => 'Status keamanan', 'two_factor' => 'Autentikasi dua faktor', 'on' => 'Aktif', 'off' => 'Nonaktif', 'update_password' => 'Ubah kata sandi', 'current_password' => 'Kata sandi saat ini', 'new_password' => 'Kata sandi baru', 'confirm_password' => 'Konfirmasi kata sandi', 'authenticator_setup' => 'Pengaturan authenticator', 'authenticator_help' => 'Aktifkan 2FA, scan QR, lalu konfirmasi kode dari authenticator.', 'refresh' => 'Muat ulang', 'enable' => 'Aktifkan', 'setup_key' => 'Kunci pengaturan', 'authenticator_url' => 'URL authenticator', 'copy' => 'Salin', 'copy_setup_key' => 'Salin kunci pengaturan', 'copy_authenticator_url' => 'Salin URL authenticator', 'copied' => 'Tersalin', 'code' => 'Kode authenticator', 'confirm_2fa' => 'Konfirmasi 2FA', 'disable_password' => 'Kata sandi untuk menonaktifkan', 'disable_2fa' => 'Nonaktifkan 2FA', 'backup_access' => 'Akses cadangan', 'backup_help' => 'Kode pemulihan hanya untuk manajemen 2FA.', 'regenerate' => 'Buat ulang', 'no_backup' => 'Kode cadangan belum tersedia dari API.', 'password_updated' => 'Kata sandi berhasil diperbarui.', 'two_factor_requested' => 'Autentikasi dua faktor diminta.', 'two_factor_confirmed' => 'Autentikasi dua faktor berhasil dikonfirmasi.', 'two_factor_disabled' => 'Autentikasi dua faktor dinonaktifkan.', 'recovery_regenerated' => 'Kode pemulihan dibuat ulang.'],
    'settings' => ['title' => 'Pengaturan', 'developer' => 'Pengembang', 'api_base_url' => 'URL dasar API'],
    'errors' => ['session_unavailable' => 'Sesi tidak tersedia.', 'api_failed' => 'Permintaan API gagal.', 'api_unavailable' => 'Koneksi tidak stabil. Menampilkan data mobile tersimpan.', 'session_expired' => 'Sesi berakhir. Silakan masuk lagi.', 'copy_failed' => 'Tidak bisa menyalin. Pilih teks lalu salin manual.'],
];
